config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users

  resources :favorites do
    collection do
      get 'search'
    end
  end
  
  resources :destinations do
    collection do
      get 'search'
    end
  end
  
  resources :dorms do
    collection do
      get 'search'
    end
  end
  resources :libraries do
    collection do
      get 'search'
    end
  end
  resources :foods do
    collection do
      get 'search'
    end
  end
  

  root "destinations#index"

  get 'map' => 'destinations#map'

  get 'routes' => 'destinations#popular_routes'

end

app/models/favorite.rb
class Favorite < ActiveRecord::Base
	searchkick
	
	belongs_to :user
	
	geocoded_by :address 
	after_validation :geocode, :if => :address_changed?

	has_attached_file :image, :styles => { :medium => "400x400#" }
  	#validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
  	validates_attachment_content_type :image, :content_type => %w(image/jpeg image/jpg image/png) 

  	has_many :directions

  	#these are the manditory fields for the destination
	validates :name, :description, :image, presence: true

  	
 	accepts_nested_attributes_for :directions, reject_if: proc { |attributes| attributes['step'].blank? }, allow_destroy: true
 	#accepts_nested_attributes_for :locations, reject_if: proc { |attributes| attributes['name'].blank? }, allow_destroy: true
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  require 'httparty'

  
	before_action :find_favorite, only: [:show, :edit, :update, :destroy]

	def index
    	@user_ip = request.remote_ip
    	@building = request_building_api()
    	@bus = request_bus_api()
		@body = JSON.parse(@bus.body)
		

		@favorite = Favorite.all.order("created_at DESC")
	end

	def show
		@current_location = "9 Fraternity Row"
		@user_ip = request.location
	end

	def new
		@favorite = Favorite.new
	end

	def create
		@favorite = Favorite.new(favorite_params)

		if @favorite.save
			redirect_to @favorite, notice: "Successfully created new favorite"
		else
			render 'new'
		end
	end

	def edit
	end

	def update
		if @favorite.update(favorite_params)
			redirect_to @favorite
		else
			render 'edit'
		end
	end

	def destroy
		@favorite.destroy
		redirect_to root_path, notice: "Successfully deleted the favorite"
	end

	def favorite_params
		params.require(:favorite).permit(:name, :description, :image, :address, :latitude, :longitude, directions_attributes: [:id, :step, :_destroy])
	end

	private

	def find_favorite
		@favorite = Favorite.find(params[:id])
	end
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/views/favorites/_form.html.haml
= simple_form_for @favorite, html: {multipart: true } do |f|
	.panel-body
		= f.input :name, input_html: {class: 'form-control'}
		= f.input :description, input_html: {class: 'form-control'}
		= f.input :image, input_html: {class: 'form-control'}
		= f.input :address, input_html: {class: 'form-control'}
		%p or
		= f.input :latitude, input_html: {class: 'form-control'}
		= f.input :longitude, input_html: {class: 'form-control'}

		.row
			.col-md-6
				%h3 Directions
				
		= f.button :submit, class: 'btn btn-primary'

app/views/favorites/edit.html.haml
%h1 Edit Favorites

= render 'form'

app/views/favorites/index.html.haml
<script src="//maps.google.com/maps/api/js?v=3.13&amp;sensor=false&amp;libraries=geometry" type="text/javascript"></script>
<script src='//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js' type='text/javascript'></script>


.row
	.col-md-12
		= link_to "Add Location to favorites", 'favorites/new', class: "btn btn-default"
%br

.row
	- @favorite.each_slice(3) do |favorites|
		- favorites.each do |favorite|
			.col-md-4
				.destination
					.image_wrapper
						= link_to favorite do
							= image_tag favorite.image.url(:medium)
					%h2= link_to favorite.name, favorite

.row
	.col-md-12
		= link_to "Back", root_path, class: "btn btn-default"


/ #####################  JAVASCRIPT FOR THE MAP  ##################################
:javascript
	handler = Gmaps.build('Google');
	handler.buildMap({ provider: {}, internal: {id: 'map'}}, function(){
		markers = handler.addMarkers([
			{
				"lat": 38.983294,
				"lng": -76.934627,
				"picture": {
				"url": "https://addons.cdn.mozilla.net/img/uploads/addon_icons/13/13028-64.png",
				"width":  36,
				"height": 36
			},
			"infowindow": "hello!"
		}
		]);
		handler.bounds.extendWith(markers);
		handler.fitMapToBounds();
	});

app/views/favorites/new.html.haml
.row
	.col-md-6
		%h1 New Favorite
		.pull-left
			= form_tag search_destinations_path, method: :get, class: "navbar-form navbar-right", role: "search" do
				= text_field_tag :search, params[:search], class: "form-control"
				= submit_tag "Search", name: nil, class: "btn btn-default"
	.col-md-6
		%h1 Custom Destination
		= render 'form'
%br/

= link_to "Back", root_path, class: "btn btn-default"

app/views/favorites/show.html.haml
<script src="//maps.google.com/maps/api/js?v=3.13&amp;sensor=false&amp;libraries=geometry" type="text/javascript"></script>
<script src='//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js' type='text/javascript'></script>

.main_content
	#destination_top.row
		.col-md-4
			= image_tag @favorite.image.url(:medium), class: "destination_image"
		.col-md-8
			#destination_info
				%h1= @favorite.name
				%p.description= @favorite.description 
				%p.description
					= @current_location 
					>
					= @favorite.address
					%br
					= @favorite.longitude
					= @favorite.latitude
					%br
						%br
							= @user_ip
	.row
		.col-md-4
			#map
		.col-md-8
			#directions
				%h2 Directions
				%ul
					

	.row
		.col-md-12
			= link_to "Back", '/favorites', class: "btn btn-default"
			- if user_signed_in?
				= link_to "Edit", edit_favorite_path, class: "btn btn-default"
				= link_to "Delete", favorite_path, method: :delete, data: {confirm: "Are you sure?" }, class: "btn btn-default"



/ #####################  JAVASCRIPT FOR THE MAP  ##################################
:javascript
	handler = Gmaps.build('Google');
	handler.buildMap({ provider: {}, internal: {id: 'map'}}, function(){
		markers = handler.addMarkers([
			{
				"lat": 38.983294,
				"lng": -76.934627,
				"picture": {
				"url": "https://addons.cdn.mozilla.net/img/uploads/addon_icons/13/13028-64.png",
				"width":  36,
				"height": 36
			},
			"infowindow": "hello!"
		}
		]);
		handler.bounds.extendWith(markers);
		handler.fitMapToBounds();
	});