config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users

  resources :favorites do
    collection do
      get 'search'
    end
  end
  
  resources :destinations do
    collection do
      get 'search'
    end
  end
  
  resources :dorms do
    collection do
      get 'search'
    end
  end
  resources :libraries do
    collection do
      get 'search'
    end
  end
  resources :foods do
    collection do
      get 'search'
    end
  end
  

  root "destinations#index"

  get 'map' => 'destinations#map'

  get 'routes' => 'destinations#popular_routes'

end

app/models/destination.rb
class Destination < ActiveRecord::Base
	searchkick
	
	belongs_to :user
	
	geocoded_by :address
	#geocoded_by :ip_address, :latitude => :latitude, :longitude => :longitude 
	after_validation :geocode

	has_attached_file :image, :styles => { :medium => "400x400#" }
  	#validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
  	validates_attachment_content_type :image, :content_type => %w(image/jpeg image/jpg image/png) 

  	has_many :directions

  	#these are the manditory fields for the destination
	validates :title, :description, :image, presence: true

  	
 	accepts_nested_attributes_for :directions, reject_if: proc { |attributes| attributes['step'].blank? }, allow_destroy: true
 	#accepts_nested_attributes_for :locations, reject_if: proc { |attributes| attributes['name'].blank? }, allow_destroy: true
end

app/controllers/destinations_controller.rb
class DestinationsController < ApplicationController
	
	require 'httparty'

	before_action :find_destination, only: [:show, :edit, :update, :destroy]


	def search
	    if params[:search].present?
			@destinations = Destination.search(params[:search])
		else
			@destinations = Destination.all
		end
	end


	def index
		# Gets the users IP adress using ruby geocoder
    	@user_ip = remote_ip()

    	# Makes calls to UMD.io api
    	@building = request_building_api()
    	@bus = request_bus_api()
    	@response = @bus.parsed_response["predictions"]
		@body = JSON.parse(@bus.body)


		@destination = Destination.all.order("title ASC")
	end

	def show
		@user_ip = remote_ip()
	end

	def new
		@destination = current_user.destinations.build
	end

	def create
		@destination = current_user.destinations.build(destination_params)

		if @destination.save
			redirect_to @destination, notice: "Successfully created new destination"
		else
			render 'new'
		end
	end

	def edit
	end

	def update
		if @destination.update(destination_params)
			redirect_to @destination
		else
			render 'edit'
		end
	end

	def destroy
		@destination.destroy
		redirect_to root_path, notice: "Successfully deleted the destination"
	end

	def destination_params
		params.require(:destination).permit(:title, :description, :image, :address, :latitude, :longitude, directions_attributes: [:id, :step, :_destroy])
	end

	private

	def find_destination
		@destination = Destination.find(params[:id])
	end

end

app/helpers/destinations_helper.rb
module DestinationsHelper
end

app/views/destinations/_direction_fields.html.haml
.form-inline.clearfix
	.nested-fields
		= f.input :step, input_html: { class: 'form-input form-control' }
		= link_to_remove_association "Remove Step", f, class: "btn btn-default form-button"

app/views/destinations/_form.html.haml
= simple_form_for @destination, html: {multipart: true } do |f|
	- if @destination.errors.any?
		#errors
		%p
			= @destination.errors.count
			Prevented this destination from saving
		%ul
			- @destination.errors.full_messages.each do |msg|
				%li = msg
	.panel-body
		= f.input :title, input_html: {class: 'form-control'}
		= f.input :description, input_html: {class: 'form-control'}
		= f.input :image, input_html: {class: 'form-control'}
		= f.input :address, input_html: {class: 'form-control'}
		%p or
		= f.input :latitude, input_html: {class: 'form-control'}
		= f.input :longitude, input_html: {class: 'form-control'}

		.row
			.col-md-6
				%h3 Directions
				#directions
					= f.simple_fields_for :directions do |direction|
						= render 'direction_fields', f: direction
					.links
						= link_to_add_association 'Add Step', f, :directions, class: "btn btn-default add-button"

		= f.button :submit, class: 'btn btn-primary'

app/views/destinations/edit.html.haml
%h1 Edit Destination

= render 'form'

app/views/destinations/index.html.haml
<script src="//maps.google.com/maps/api/js?v=3.13&amp;sensor=false&amp;libraries=geometry" type="text/javascript"></script>
<script src='//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js' type='text/javascript'></script>


- @destination.each_slice(3) do |destinations|
	- destinations.each do |destination|
		.col-md-4
			.destination
				.image_wrapper
					= link_to destination do
						= image_tag destination.image.url(:medium)
				%h2= link_to destination.title.capitalize, destination
	


%h2= @user_ip
%h2= @locate_ip
%br
%br
%h1= @building.body
%h2= @response




/ #####################  JAVASCRIPT FOR THE MAP  ##################################
:javascript
	handler = Gmaps.build('Google');
	handler.buildMap({ provider: {}, internal: {id: 'map'}}, function(){
		markers = handler.addMarkers([
			{
				"lat": 38.983294,
				"lng": -76.934627,
				"picture": {
				"url": "https://addons.cdn.mozilla.net/img/uploads/addon_icons/13/13028-64.png",
				"width":  36,
				"height": 36
			},
			"infowindow": "hello!"
		}
		]);
		handler.bounds.extendWith(markers);
		handler.fitMapToBounds();
	});

app/views/destinations/new.html.haml
%h1 New Destination
= render 'form'

%br/

= link_to "Back", root_path, class: "btn btn-default"

app/views/destinations/search.html.haml
.row
	- @destinations.each do |destination|
		.col-md-4
			.destination
				.image_wrapper
					= link_to destination.title do
						= image_tag destination.image.url(:medium)
				%h2= link_to destination.title.capitalize, destination

app/views/destinations/show.html.haml
<script src="//maps.google.com/maps/api/js?v=3.13&amp;sensor=false&amp;libraries=geometry" type="text/javascript"></script>
<script src='//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js' type='text/javascript'></script>

.main_content
	#destination_top.row
		.col-md-4
			= image_tag @destination.image.url(:medium), class: "destination_image"
		.col-md-8
			#destination_info
				%h1= @destination.title
				%p.description= @destination.description 
				%p.description
					= @user_ip.address
					>
					= @destination.address
					%br
					= @destination.longitude
					= @destination.latitude
					%br
						%br
							= @user_ip
						Submitted by:
						= @destination.user.email
	.row
		.col-md-4
			#map
		.col-md-8
			#directions
				%h2 Directions
				%ul
					- @destination.directions.each do |direction|
						%li= direction.step

	.row
		.col-md-12
			= link_to "Back", root_path, class: "btn btn-default"
			- if user_signed_in?
				= link_to "Edit", edit_destination_path, class: "btn btn-default"
				= link_to "Delete", destination_path, method: :delete, data: {confirm: "Are you sure?" }, class: "btn btn-default"



/ #####################  JAVASCRIPT FOR THE MAP  ##################################
:javascript
	handler = Gmaps.build('Google');
	handler.buildMap({ provider: {}, internal: {id: 'map'}}, function(){
		var markers = handler.addMarkers([
			{ lat: 46, lng: 3.7},
			{ lat: 45, lng: 4},
			{ lat: 47, lng: 3.5},
			{ lat: 49, lng: 4},
			{ lat: 51, lng: 3.5}
		]);
		handler.bounds.extendWith(markers);
		handler.fitMapToBounds();
	});


	